from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('', views.home, name="home-page"),
    path('login', auth_views.LoginView.as_view(template_name = 'posApp/login.html',redirect_authenticated_user=True), name="login"),
    path('userlogin', views.login_user, name="login-user"),
    path('logout', views.logoutuser, name="logout"),
    path('category', views.category, name="category-page"),
    path('manage_category', views.manage_category, name="manage_category-page"),
    path('save_category', views.save_category, name="save-category-page"),
    path('delete_category', views.delete_category, name="delete-category"),
    path('products', views.products, name="product-page"),
    path('manage_products', views.manage_products, name="manage_products-page"),
    path('test', views.test, name="test-page"),
    path('save_product', views.save_product, name="save-product-page"),
    path('delete_product', views.delete_product, name="delete-product"),
    path('pos', views.pos, name="pos-page"),
    # path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
    path('delete-multiple-sales/', views.delete_multiple_sales, name='delete-multiple-sales'),
    path('customerdatabase/', views.customerdatabase, name='customerdatabase-page'),
    path('delete_customer/', views.delete_customer, name='delete_customer'),
    path('get_customer_by_phone/', views.get_customer_by_phone, name='get_customer_by_phone'),
    path('add_user/', views.add_user, name='add_user'),
    path('report/', views.report, name="report"),
    path('weekly_report_detail/<int:week_number>/', views.weekly_report_detail, name="weekly_report_detail"),
    path('add_weekly_debit/<int:week_number>/', views.add_weekly_debit, name="add_weekly_debit"),
    path('edit_weekly_debit/<int:pk>/', views.edit_weekly_debit, name="edit_weekly_debit"),
    path('delete_weekly_debit/<int:pk>/', views.delete_weekly_debit, name="delete_weekly_debit"),
    path('export_weekly_report/<int:week_number>/', views.export_weekly_report, name="export_weekly_report"),
    path('export_monthly_report/', views.export_monthly_report, name="export_monthly_report"),
    path('export_date_range_report/', views.export_date_range_report, name="export_date_range_report"),
    path('email_monthly_report/', views.email_monthly_report, name="email_monthly_report"),
    path('email_date_range_report/', views.email_date_range_report, name="email_date_range_report"),
    path('email_weekly_report/<int:week_number>/', views.email_weekly_report, name="email_weekly_report"),
    path('employee/', views.employee, name="employee"),
    path('attendance/', views.attendance, name="attendance"),
    path('attendance/summary/', views.attendance_summary, name="attendance_summary"),
    path('employees/delete/<int:pk>/', views.delete_employee, name='delete_employee'),
    path('employees/edit/<int:pk>/', views.edit_employee, name='edit_employee'),
    path('mark_attendance/<str:date>/', views.mark_attendance, name='mark_attendance'),
    # path('employees', views.employees, name="employee-page"),
    # path('manage_employees', views.manage_employees, name="manage_employees-page"),
    # path('save_employee', views.save_employee, name="save-employee-page"),
    # path('delete_employee', views.delete_employee, name="delete-employee"),
    # path('view_employee', views.view_employee, name="view-employee-page"),
]