# Generated by Django 5.1.1 on 2024-10-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_alter_salesitems_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
