# Generated by Django 5.1.1 on 2024-10-01 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_alter_sales_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.sales'),
        ),
    ]
