# Generated by Django 5.1.1 on 2024-10-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_alter_sales_token_no_alter_salesitems_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(related_name='sales', to='posApp.products'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.CharField(default='1 - (Product Name)', max_length=255),
        ),
    ]
