# Generated by Django 5.1.1 on 2024-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_remove_sales_products_alter_sales_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(related_name='sales', to='posApp.products'),
        ),
    ]
