# Generated by Django 5.1.1 on 2024-10-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_sales_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
    ]
