# Generated by Django 5.1.1 on 2024-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_remove_sales_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.CharField(default=1),
        ),
    ]
