# Generated by Django 5.1.1 on 2024-10-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_alter_sales_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.IntegerField(default=1),
        ),
    ]
