# Generated by Django 5.1.1 on 2024-10-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_alter_sales_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posApp.sales'),
        ),
    ]
