# Generated by Django 5.1.1 on 2024-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_alter_salesitems_sale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='token_no',
        ),
        migrations.AddField(
            model_name='sales',
            name='token_no_display',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
