# Generated by Django 5.1.1 on 2024-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_remove_sales_token_no_sales_token_no_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='token_no_display',
        ),
        migrations.AddField(
            model_name='sales',
            name='token_no',
            field=models.IntegerField(default=1),
        ),
    ]
