# Generated by Django 5.1.1 on 2024-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_remove_sales_token_no_display_sales_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.CharField(default=1),
        ),
    ]
