# Generated by Django 5.1.1 on 2024-10-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_alter_sales_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='raw_token_no',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
