# Generated by Django 5.1.1 on 2024-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_sales_raw_token_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='raw_token_no',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='token_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
