# Generated by Django 5.1.1 on 2024-11-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0018_alter_sales_raw_token_no_alter_sales_token_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='amount_change',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tendered_amount',
        ),
    ]
