# Generated by Django 5.1.1 on 2025-08-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0021_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='daily_wages',
            new_name='daily_wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
