# Generated by Django 5.1.1 on 2026-05-08 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydebit',
            name='debit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
