# Generated by Django 5.1.1 on 2026-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0024_weeklydebit_debit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
