# Generated by Django 5.1.1 on 2026-05-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0025_employee_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='order',
        ),
    ]
