# Generated by Django 5.1.1 on 2026-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0026_remove_employee_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
